-define(TYPE, 8/unsigned-integer).
-define(VER, 8/unsigned-integer).
-define(LAT, 16/signed-little-integer).
-define(LON, 16/signed-little-integer).
-define(LAT_EXP, 32/unsigned-little-integer).
-define(LON_EXP, 32/unsigned-little-integer).
-define(TIMESTAMP, 32/unsigned-little-integer).
-define(BIN_DEV_NAME, 96/bitstring).
-define(TRACK_NAME, bitstring).
-define(SPEED, 16/unsigned-little-integer).

-define(DEV_NAME_LEN, 12).
-define(REF_SIZE, 128).
